---
title: "Dunkeld Heating Oil Prices plot"
---

This plot was last updated at `r strftime(Sys.time(), format = "%B %d, %Y %H:%M:%S")`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r auth, include=FALSE}
gmailr::gm_auth_configure(path = "gmail_api_creds.json")

gmailr::gm_auth(
  email = "dunkeld.oil.club.r@gmail.com",
  cache = ".secret"
)
```
```{r get_messages, include=FALSE}
message_ids <- gmailr::gm_messages(search = "The Oil-Club") |>
  gmailr::gm_id()

existing_data <- arrow::read_parquet("data/data.parquet")

new_ids <- setdiff(message_ids, existing_data$id)
```

```{r parse_new_data, include=FALSE}
if (length(new_ids) != 0) {
  messages <- purrr::map(new_ids, gmailr::gm_message)

  dates <- purrr::map_chr(messages, gmailr::gm_date) |>
    lubridate::dmy_hms()

  prices <- purrr::map_dbl(messages, ~ .x[["snippet"]] |>
    stringr::str_extract(
      pattern = "£([0-1]\\.[0-9]{4}) ppl",
      group = 1
    ) |>
    as.numeric())

  new_data <- tibble::tibble(
    id = new_ids,
    date = dates,
    price = prices
  )
} else {
  new_data <- tibble::tibble()
}
```

```{r combine_data, include=FALSE}
chart_data <- dplyr::bind_rows(
  existing_data,
  new_data
)

arrow::write_parquet(
  chart_data,
  "data/data.parquet",
  version = "latest",
  compression = "zstd"
)
```

```{r plot, echo=FALSE}
plot <- chart_data |>
  ggplot2::ggplot(ggplot2::aes(x = date, y = price)) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::scale_x_datetime(
    name = "Date",
    labels = scales::label_date_short(),
    breaks = scales::breaks_width("week")
  ) +
  ggplot2::scale_y_continuous(
    name = "Oil Price",
    labels = scales::label_dollar(prefix = "£")
  ) +
  ggplot2::theme_minimal()

plotly::ggplotly(plot) |>
  plotly::config(displayModeBar = FALSE)
```
